"""Add phone column to person table

Revision ID: bc3e10ce5ca5
Revises: 
Create Date: 2025-03-27 21:22:44.821968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3e10ce5ca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('skin_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('makeup_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availablity', sa.String(length=200), nullable=True))
        batch_op.alter_column('experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('makeup_artist', schema=None) as batch_op:
        batch_op.alter_column('experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('availablity')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('skin_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
